### ISSUE TITLE
Реализовать класс Trend

### ISSUE THREAD

**Issue by Neliitsme** [Neliitsme/Recommendation-Service#5]
Добавить функции для взаимодействия. При необходимости так же добавить функции для взаимодействия с TrendingItem.

Пример: [Пример 1](https://github.com/andrsuh/tiny-event-sourcing/blob/master-2.0/tiny-event-sourcing-spring-app/src/main/kotlin/ru.quipy/bankDemo/accounts/logic/Account.kt), [Пример 2](https://github.com/andrsuh/tiny-event-sourcing/blob/master-2.0/tiny-event-sourcing-spring-app/src/main/kotlin/ru.quipy/bankDemo/transfers/logic/TransaferTransaction.kt)

За эвенты этого класса можно взять в последнюю очередь, они не особо важны

## Что представляет из себя этот агрегат?

По сути это агрегат для отслеживания метрик. В конкретности TrendingItem - для отслеживания кол-ва **!заказов!** для того чтобы можно было легко понять что более популярно, а что - менее. 
Если есть идеи для других метрик - вперед, но лучше обсудить, а еще лучше не придумывать что-то, что мы не успеем реализовать.

**Comment by maypink** [comment]
partially closed by #10
