### ISSUE TITLE
Написать эвенты для Trend

### ISSUE THREAD

**Issue by Neliitsme** [Neliitsme/Recommendation-Service#7]
Если вдруг тренд поменялся и какой-то товар стал популярнее другого. Мне кажется будет лишним, но это не должно быть сложно в имплементации

**Comment by Neliitsme** [comment]
Часть сделана в #10, стоит добавить эвент об изменении тренда (Например, какой-то предмет поднялся в популярности)

**Comment by maypink** [comment]
partially closed by #10
